### ISSUE TITLE
Add xml support to request matching

### ISSUE THREAD

**Issue by tobias-jueschke** [HBOCodeLabs/wiremock-captain#181]
## Expected Behavior

The enum `MatchingAttributes` should also contain `equalToXml` and `matchesXPath`.

## Actual Behavior

Currently it is just possible to make use of xml request matching by adding the value without the enum like:

```typescript
const features: IWireMockFeatures = {
  requestBodyFeature: 'equalToXml' as MatchingAttributes,
};
```

## Specifications

- Version: 3.2.0

**Comment by satvik-s** [comment]
#185
