### ISSUE TITLE
Latest published version contains a security vulnerability

### ISSUE THREAD

**Issue by timv88** [HBOCodeLabs/wiremock-captain#439]
## Expected Behavior
The latest `wiremock-captain` package version on npm does not contain any security vulnerabilities 

## Actual Behavior
The latest `wiremock-captain` package version `3.3.0` contains a security vulnerability in the Axios dependency

## Steps to Reproduce the Problem
```
npm install wiremock-captain
npm audit
```

## Specifications

- Version: 3.3.0
- Platform: n/a
- Subsystem: n/a

**Comment by satvik-s** [comment]
thanks @timv88 for reporting it.

the main branch should have the fixed changes but unfortunately i am running into some issues publishing the latest version with the updated deps. will try to get it out soon
