### ISSUE TITLE
How to set `formParameters`?

### ISSUE THREAD

**Issue by akefirad** [HBOCodeLabs/wiremock-captain#546]
Hi there,

I'm trying to create a stub with some form parameters. According to the [doc](https://wiremock.org/docs/request-matching/#request-with-form-parameters), I need to set `formParameters`, but I cannot find it in this library.
Is this not implemented or am I missing something.

Thanks.

**Comment by akefirad** [comment]
I’d be happy to help. Let me take a look and see what/if I can do anything (disclaimer, TS is not my strength 😁)

**Comment by satvik-s** [comment]
@akefirad I was able to get to it

feel free to take a look at the pull request. i will try to merge that and create a release later today

**Comment by satvik-s** [comment]
@akefirad https://www.npmjs.com/package/wiremock-captain/v/3.4.0 should solve it

thanks for raising the issue!

**Comment by akefirad** [comment]
Thanks for quick response!
