### ISSUE TITLE
Cannot register a request that uses a string body

### ISSUE THREAD

**Issue by Rigellute** [HBOCodeLabs/wiremock-captain#55]
## Expected Behavior

To be able to register a request that uses a form-encoded body.

## Actual Behavior

Any request that uses a string body silently fails to register.

## Steps to Reproduce the Problem

```ts
const authHeaders = {
  'Content-Type': 'application/x-www-form-urlencoded',
};

await mock.register(
  { method: 'POST', endpoint: '/auth', body: ' username=username&password=password', headers: authHeaders },
  { status: 200, body: { access_token: 'string' } },
);

// sending a matching request will 404

// Or list the mappings
const mappings = await mock.getAllMappings();
console.log(mappings); // empty array that shows the register silently failed

```

## Specifications

- Version: 1.6.0
- Platform: Windows
- Subsystem: WSL2

**Comment by satvik-s** [comment]
Hi, thanks for raising this up. I will try to look at this later today.

Meanwhile, if you have any more findings about the issue, do share them

**Comment by satvik-s** [comment]
Have you tried using `BodyType` feature as specifying `BodyType.Body`?

**Comment by satvik-s** [comment]
Looks like this is something wiremock does not have a good way to support which might limit our support too. SO thread: https://stackoverflow.com/questions/48627656/wiremock-match-request-post-by-params

**Comment by satvik-s** [comment]
@Rigellute if there is a JSON equivalent that you can come up with that will solve your case, I am happy to look at possible implementations of that in the library

to see some examples of wiremock JSON requests: http://wiremock.org/docs/stubbing/

**Comment by Rigellute** [comment]
@satvik-s thanks for looking into this. I've not looked into a JSON equivalent workaround.

Although the non-JSON [Basic Stubbing](http://wiremock.org/docs/stubbing/#basic-stubbing) example from the wiremock docs should work for my usecase too (since the body is just a string).

The main issue was that the plain string body was not being registered with wiremock server itself. I've not tried v2 of this lib, which may have fixed that?

**Comment by satvik-s** [comment]
@Rigellute that might work. i would suggest trying `BodyType.Body` for that. here is an example of doing something similar: https://github.com/HBOCodeLabs/wiremock-captain/tree/main/docs/examples#return-binary-data-eg-api-with-protobuf-support

**Comment by satvik-s** [comment]
@Rigellute  were you able to figure this out? if yes, would like to close this out

**Comment by Rigellute** [comment]
Hi @satvik-s, I've not yet tried using `BodyType.Body`. 

I've pivoted away from using wiremock for the time being, so feel free to close. If I come back and this is still an issue, I'll reopen.
