### ISSUE TITLE
Reset instead of deleting mappings

### ISSUE THREAD

**Issue by danilofuchs** [HBOCodeLabs/wiremock-captain#58]
## Expected Behavior

I would like to be able to define default mappings to work with Wiremock APIs during development, and customize the responses in tests.

It would be nice to expose the `resetMappings` admin endpoint, which resets to the persisted files

## Actual Behavior

`clearAll` deletes all mapping files from disk (when using a Docker Volume).

This means I either have the default development mappings _or_ the test mappings

**Comment by satvik-s** [comment]
Thanks for the input!

To clarify, exposing [this](http://wiremock.org/docs/api/#tag/Stub-Mappings/paths/~1__admin~1mappings~1reset/post) API would be the ideal fix for you, correct? @danilofuchs

**Comment by danilofuchs** [comment]
Exactly!
I would call this API `resetMappings()` and `clearAllRequests()` sequentially to achieve my desired behavior

**Comment by satvik-s** [comment]
@danilofuchs have opened a PR. feel free to leave any feedback otherwise i will merge that and get a new release out

**Comment by satvik-s** [comment]
@danilofuchs  this got auto-closed with the merge but wondering if you tried it out yet

**Comment by danilofuchs** [comment]
@satvik-s I just tested and it works just like I expected. Thank you for the quick patch!
