### ISSUE TITLE
"export const enum" like EndpointFeature are not available at runtime

### ISSUE THREAD

**Issue by tekener** [HBOCodeLabs/wiremock-captain#68]
## Expected Behavior

I am trying to register a mock using the EntdpointFeature. Looks like i get a TypeError at runtime because the enums are defined as `const enum` that's why they are not available at runtime (https://www.typescriptlang.org/docs/handbook/enums.html#const-enums).

Maybe there is a other workaround for this problem you know but i don't get it working.

Code like this is working:

```
const features: IWireMockFeatures = { requestEndpointFeature: EndpointFeature.UrlPattern };
```

## Actual Behavior

```
TypeError: Cannot read properties of undefined (reading 'UrlPath')
```

## Steps to Reproduce the Problem

-
-

## Specifications

- Version: 2.2.1
- Platform: Node v16
- Subsystem:

**Comment by satvik-s** [comment]
Hi! Thanks for raising it up. using `const` enums was intentional and I have not seen any one run into issues yet with using it

Can you give a little more info about what command you are running, etc.?

**Comment by satvik-s** [comment]
I stumbled onto this SO thread: https://stackoverflow.com/questions/50365598/typescript-runtime-error-cannot-read-property-of-undefined-enum (in case this helps)

**Comment by satvik-s** [comment]
we have test structured like this that work w/o any issues (in `.ts` files)

```typescript
            await mock.register(
                {
                    method: 'GET',
                    endpoint: '/v1/api',
                },
                {
                    status: 200,
                },
                { ...testMockFeatures, requestEndpointFeature: EndpointFeature.UrlPath },
            );
```

**Comment by jforaker** [comment]
If you're not using ts, the import is broken.

Just check the value of the enum and use it instead of importing it, for ex:

```
        {
          requestEndpointFeature: 'urlPathPattern',
        },
```
